name: FreeCAD Export and Convert
on:
  push:
    branches:
      - main

jobs:
  export-and-convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Fetch FreeCAD
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "FreeCAD/FreeCAD"
          version: "tags/1.0.0"
          file: "FreeCAD_1.0.0-conda-Linux-x86_64-py311.AppImage"
          target: "FreeCAD.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install FreeCad
        run:  |
          sudo chown runner:docker FreeCAD.AppImage
          pwd
          chmod +x FreeCAD.AppImage
          ./FreeCAD.AppImage --appimage-extract > /dev/null
      
      - name: Export STL from FreeCAD
        run: |
          ./squashfs-root/usr/bin/python generate.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 3d-models
          path: |
            projectslot.stl
            ps-pcb-mount.stl
            pcb-slide-in-clip.stl
