name: FreeCAD Export and Convert
on:
  push:
    branches:
      - main

jobs:
  export-and-convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install FreeCAD and Assimp
        run: |
          sudo apt install software-properties-common apt-transport-https -y
          sudo add-apt-repository ppa:freecad-maintainers/freecad-daily -y
          sudo apt-get update
          sudo apt install -y freecad-daily
      
      - name: Export STL from FreeCAD
        run: |
          # Assuming your FreeCAD file is named model.FCStd
          # Adjust the filenames and paths as needed
          freecadcmd --run-script "import FreeCAD; import Import; import Mesh; doc = FreeCAD.open('projectslot.FCStd'); Mesh.export([doc.getObject("projectslot")], 'projectslot.stl')"
          freecadcmd --run-script "import FreeCAD; import Import; import Mesh; doc = FreeCAD.open('projectslot.FCStd'); Mesh.export([doc.getObject("ps-pcb-mount")], 'ps-pcb-mount.stl')"
          freecadcmd --run-script "import FreeCAD; import Import; import Mesh; doc = FreeCAD.open('projectslot.FCStd'); Mesh.export([doc.getObject("pcb-slide-in-clip")], 'ps-pcb-slide-in-clip.stl')"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 3d-models
          path: |
            projectslot.stl
            ps-pcb-mount.stl
            pcb-slide-in-clip.stl
